/// Flutter icons FlutterMenu
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterMenu
///      fonts:
///       - asset: fonts/FlutterMenu.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FlutterMenu {
  FlutterMenu._();

  static const _kFontFam = 'FlutterMenu';
//  static const String? _kFontPkg = null;

  static const IconData union_50 = IconData(0xe800, fontFamily: _kFontFam);
}
